### ISSUE TITLE
Doesn't work in some countries

### ISSUE THREAD

**Issue by ivfit** [Autodesk/ADAppRater-iOS#29]
Noticed that some countries return empty App Store details, which blocks proper functioning of ADAppRater.

E.g.
https://itunes.apple.com/RS/lookup?bundleId=com.clickgamer.AngryBirds
vs.
https://itunes.apple.com/US/lookup?bundleId=com.clickgamer.AngryBirds

I think there should be variable 'appStoreCountry' to be able to force it to 'us'.

Wondering what is the purpose of querying specific country?

**Comment by ashavit** [comment]
The purpose is to make sure one can connect and rate the app on his relevant locale store.
Added a setter anyhow, if you fell the need.
PS, If you feel you are still missing some features, feel free to commit a pull request.

**Comment by ivfit** [comment]
Thanks, but cannot access setAppStoreCountry, it is part of ADAppStoreConnector?

**Comment by ashavit** [comment]
ADAppStoreConnector now has a public setter: 
`- (void)setAppStoreCountry:(NSString *)appStoreCountry`
Did you update to latest pod version?

**Comment by ivfit** [comment]
I did update and don't see a way to access it from ADAppRater.

**Comment by ashavit** [comment]
The country is used to lookup the app in the store, in order to find it's app id for later routing to app's page.
However it seems the lookup url works fine without the country code (defaults to US is guess), and the ID is same for all countries.
So I removed the use of country altogether here (along with a toggle to revert to old flows if it breaks for some one.
This will go in to version 1.1.3
